--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: postgres-deployment
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      component: postgres
  template: 
    metadata: 
      labels: 
        component: postgres
    spec: 
      containers: 
        - 
          env: 
            - 
              name: PGPASSWORD
              valueFrom: 
                secretKeyRef: 
                  key: PGPASSWORD
                  name: pgpassword
          image: postgres
          name: postgres
          ports: 
            - 
              containerPort: 5432
          volumeMounts: 
            - 
              mountPath: /var/lib/postgressql/data
              name: postgres-storage
              subPath: postgres
      volumes: 
        - 
          name: postgres-storage
          persistentVolumeClaim: 
            claimName: database-persistent-volume-claim
